/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ShortPathRouteImport } from './routes/$shortPath'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTagsRouteImport } from './routes/api/tags'
import { Route as ApiLinksRouteImport } from './routes/api/links'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard.index'
import { Route as ApiTagsIdRouteImport } from './routes/api/tags/$id'
import { Route as ApiLinksCheckPathRouteImport } from './routes/api/links/check-path'
import { Route as ApiLinksIdRouteImport } from './routes/api/links/$id'
import { Route as ApiCampaignsIdRouteImport } from './routes/api/campaigns/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAnalyticsOverviewRouteImport } from './routes/api/analytics/overview'
import { Route as ApiAnalyticsExportDotcsvRouteImport } from './routes/api/analytics/export[.]csv'
import { Route as ProtectedDashboardTagsRouteImport } from './routes/_protected/dashboard/tags'
import { Route as ProtectedDashboardSettingsRouteImport } from './routes/_protected/dashboard/settings'
import { Route as ProtectedDashboardLinksRouteImport } from './routes/_protected/dashboard/links'
import { Route as ProtectedDashboardCampaignsRouteImport } from './routes/_protected/dashboard/campaigns'
import { Route as ProtectedDashboardLinksIndexRouteImport } from './routes/_protected/dashboard/links.index'
import { Route as ApiLinksIdTagsRouteImport } from './routes/api/links/$id/tags'
import { Route as ApiLinksIdDisableRouteImport } from './routes/api/links/$id/disable'
import { Route as ApiLinksIdCampaignsRouteImport } from './routes/api/links/$id/campaigns'
import { Route as ApiLinksIdArchiveRouteImport } from './routes/api/links/$id/archive'
import { Route as ApiLinksIdAnalyticsRouteImport } from './routes/api/links/$id/analytics'
import { Route as ProtectedDashboardLinksNewRouteImport } from './routes/_protected/dashboard/links/new'
import { Route as ProtectedDashboardLinksIdRouteImport } from './routes/_protected/dashboard/links/$id'
import { Route as ProtectedDashboardLinksIdEditRouteImport } from './routes/_protected/dashboard/links/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortPathRoute = ShortPathRouteImport.update({
  id: '/$shortPath',
  path: '/$shortPath',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsRoute = ApiTagsRouteImport.update({
  id: '/api/tags',
  path: '/api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinksRoute = ApiLinksRouteImport.update({
  id: '/api/links',
  path: '/api/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ApiTagsIdRoute = ApiTagsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTagsRoute,
} as any)
const ApiLinksCheckPathRoute = ApiLinksCheckPathRouteImport.update({
  id: '/check-path',
  path: '/check-path',
  getParentRoute: () => ApiLinksRoute,
} as any)
const ApiLinksIdRoute = ApiLinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLinksRoute,
} as any)
const ApiCampaignsIdRoute = ApiCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCampaignsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsOverviewRoute = ApiAnalyticsOverviewRouteImport.update({
  id: '/api/analytics/overview',
  path: '/api/analytics/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsExportDotcsvRoute =
  ApiAnalyticsExportDotcsvRouteImport.update({
    id: '/api/analytics/export.csv',
    path: '/api/analytics/export.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedDashboardTagsRoute = ProtectedDashboardTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardSettingsRoute =
  ProtectedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardLinksRoute = ProtectedDashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardCampaignsRoute =
  ProtectedDashboardCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardLinksIndexRoute =
  ProtectedDashboardLinksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardLinksRoute,
  } as any)
const ApiLinksIdTagsRoute = ApiLinksIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ApiLinksIdRoute,
} as any)
const ApiLinksIdDisableRoute = ApiLinksIdDisableRouteImport.update({
  id: '/disable',
  path: '/disable',
  getParentRoute: () => ApiLinksIdRoute,
} as any)
const ApiLinksIdCampaignsRoute = ApiLinksIdCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => ApiLinksIdRoute,
} as any)
const ApiLinksIdArchiveRoute = ApiLinksIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiLinksIdRoute,
} as any)
const ApiLinksIdAnalyticsRoute = ApiLinksIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ApiLinksIdRoute,
} as any)
const ProtectedDashboardLinksNewRoute =
  ProtectedDashboardLinksNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedDashboardLinksRoute,
  } as any)
const ProtectedDashboardLinksIdRoute =
  ProtectedDashboardLinksIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedDashboardLinksRoute,
  } as any)
const ProtectedDashboardLinksIdEditRoute =
  ProtectedDashboardLinksIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedDashboardLinksIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortPath': typeof ShortPathRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/links': typeof ApiLinksRouteWithChildren
  '/api/tags': typeof ApiTagsRouteWithChildren
  '/dashboard/campaigns': typeof ProtectedDashboardCampaignsRoute
  '/dashboard/links': typeof ProtectedDashboardLinksRouteWithChildren
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard/tags': typeof ProtectedDashboardTagsRoute
  '/api/analytics/export.csv': typeof ApiAnalyticsExportDotcsvRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRoute
  '/api/links/$id': typeof ApiLinksIdRouteWithChildren
  '/api/links/check-path': typeof ApiLinksCheckPathRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/dashboard/links/$id': typeof ProtectedDashboardLinksIdRouteWithChildren
  '/dashboard/links/new': typeof ProtectedDashboardLinksNewRoute
  '/api/links/$id/analytics': typeof ApiLinksIdAnalyticsRoute
  '/api/links/$id/archive': typeof ApiLinksIdArchiveRoute
  '/api/links/$id/campaigns': typeof ApiLinksIdCampaignsRoute
  '/api/links/$id/disable': typeof ApiLinksIdDisableRoute
  '/api/links/$id/tags': typeof ApiLinksIdTagsRoute
  '/dashboard/links/': typeof ProtectedDashboardLinksIndexRoute
  '/dashboard/links/$id/edit': typeof ProtectedDashboardLinksIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortPath': typeof ShortPathRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/links': typeof ApiLinksRouteWithChildren
  '/api/tags': typeof ApiTagsRouteWithChildren
  '/dashboard/campaigns': typeof ProtectedDashboardCampaignsRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard/tags': typeof ProtectedDashboardTagsRoute
  '/api/analytics/export.csv': typeof ApiAnalyticsExportDotcsvRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRoute
  '/api/links/$id': typeof ApiLinksIdRouteWithChildren
  '/api/links/check-path': typeof ApiLinksCheckPathRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/dashboard/links/$id': typeof ProtectedDashboardLinksIdRouteWithChildren
  '/dashboard/links/new': typeof ProtectedDashboardLinksNewRoute
  '/api/links/$id/analytics': typeof ApiLinksIdAnalyticsRoute
  '/api/links/$id/archive': typeof ApiLinksIdArchiveRoute
  '/api/links/$id/campaigns': typeof ApiLinksIdCampaignsRoute
  '/api/links/$id/disable': typeof ApiLinksIdDisableRoute
  '/api/links/$id/tags': typeof ApiLinksIdTagsRoute
  '/dashboard/links': typeof ProtectedDashboardLinksIndexRoute
  '/dashboard/links/$id/edit': typeof ProtectedDashboardLinksIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortPath': typeof ShortPathRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/links': typeof ApiLinksRouteWithChildren
  '/api/tags': typeof ApiTagsRouteWithChildren
  '/_protected/dashboard/campaigns': typeof ProtectedDashboardCampaignsRoute
  '/_protected/dashboard/links': typeof ProtectedDashboardLinksRouteWithChildren
  '/_protected/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/_protected/dashboard/tags': typeof ProtectedDashboardTagsRoute
  '/api/analytics/export.csv': typeof ApiAnalyticsExportDotcsvRoute
  '/api/analytics/overview': typeof ApiAnalyticsOverviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRoute
  '/api/links/$id': typeof ApiLinksIdRouteWithChildren
  '/api/links/check-path': typeof ApiLinksCheckPathRoute
  '/api/tags/$id': typeof ApiTagsIdRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/dashboard/links/$id': typeof ProtectedDashboardLinksIdRouteWithChildren
  '/_protected/dashboard/links/new': typeof ProtectedDashboardLinksNewRoute
  '/api/links/$id/analytics': typeof ApiLinksIdAnalyticsRoute
  '/api/links/$id/archive': typeof ApiLinksIdArchiveRoute
  '/api/links/$id/campaigns': typeof ApiLinksIdCampaignsRoute
  '/api/links/$id/disable': typeof ApiLinksIdDisableRoute
  '/api/links/$id/tags': typeof ApiLinksIdTagsRoute
  '/_protected/dashboard/links/': typeof ProtectedDashboardLinksIndexRoute
  '/_protected/dashboard/links/$id/edit': typeof ProtectedDashboardLinksIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$shortPath'
    | '/health'
    | '/login'
    | '/dashboard'
    | '/api/campaigns'
    | '/api/links'
    | '/api/tags'
    | '/dashboard/campaigns'
    | '/dashboard/links'
    | '/dashboard/settings'
    | '/dashboard/tags'
    | '/api/analytics/export.csv'
    | '/api/analytics/overview'
    | '/api/auth/$'
    | '/api/campaigns/$id'
    | '/api/links/$id'
    | '/api/links/check-path'
    | '/api/tags/$id'
    | '/dashboard/'
    | '/dashboard/links/$id'
    | '/dashboard/links/new'
    | '/api/links/$id/analytics'
    | '/api/links/$id/archive'
    | '/api/links/$id/campaigns'
    | '/api/links/$id/disable'
    | '/api/links/$id/tags'
    | '/dashboard/links/'
    | '/dashboard/links/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$shortPath'
    | '/health'
    | '/login'
    | '/api/campaigns'
    | '/api/links'
    | '/api/tags'
    | '/dashboard/campaigns'
    | '/dashboard/settings'
    | '/dashboard/tags'
    | '/api/analytics/export.csv'
    | '/api/analytics/overview'
    | '/api/auth/$'
    | '/api/campaigns/$id'
    | '/api/links/$id'
    | '/api/links/check-path'
    | '/api/tags/$id'
    | '/dashboard'
    | '/dashboard/links/$id'
    | '/dashboard/links/new'
    | '/api/links/$id/analytics'
    | '/api/links/$id/archive'
    | '/api/links/$id/campaigns'
    | '/api/links/$id/disable'
    | '/api/links/$id/tags'
    | '/dashboard/links'
    | '/dashboard/links/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$shortPath'
    | '/_protected'
    | '/health'
    | '/login'
    | '/_protected/dashboard'
    | '/api/campaigns'
    | '/api/links'
    | '/api/tags'
    | '/_protected/dashboard/campaigns'
    | '/_protected/dashboard/links'
    | '/_protected/dashboard/settings'
    | '/_protected/dashboard/tags'
    | '/api/analytics/export.csv'
    | '/api/analytics/overview'
    | '/api/auth/$'
    | '/api/campaigns/$id'
    | '/api/links/$id'
    | '/api/links/check-path'
    | '/api/tags/$id'
    | '/_protected/dashboard/'
    | '/_protected/dashboard/links/$id'
    | '/_protected/dashboard/links/new'
    | '/api/links/$id/analytics'
    | '/api/links/$id/archive'
    | '/api/links/$id/campaigns'
    | '/api/links/$id/disable'
    | '/api/links/$id/tags'
    | '/_protected/dashboard/links/'
    | '/_protected/dashboard/links/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortPathRoute: typeof ShortPathRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ApiCampaignsRoute: typeof ApiCampaignsRouteWithChildren
  ApiLinksRoute: typeof ApiLinksRouteWithChildren
  ApiTagsRoute: typeof ApiTagsRouteWithChildren
  ApiAnalyticsExportDotcsvRoute: typeof ApiAnalyticsExportDotcsvRoute
  ApiAnalyticsOverviewRoute: typeof ApiAnalyticsOverviewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shortPath': {
      id: '/$shortPath'
      path: '/$shortPath'
      fullPath: '/$shortPath'
      preLoaderRoute: typeof ShortPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags': {
      id: '/api/tags'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/links': {
      id: '/api/links'
      path: '/api/links'
      fullPath: '/api/links'
      preLoaderRoute: typeof ApiLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/api/tags/$id': {
      id: '/api/tags/$id'
      path: '/$id'
      fullPath: '/api/tags/$id'
      preLoaderRoute: typeof ApiTagsIdRouteImport
      parentRoute: typeof ApiTagsRoute
    }
    '/api/links/check-path': {
      id: '/api/links/check-path'
      path: '/check-path'
      fullPath: '/api/links/check-path'
      preLoaderRoute: typeof ApiLinksCheckPathRouteImport
      parentRoute: typeof ApiLinksRoute
    }
    '/api/links/$id': {
      id: '/api/links/$id'
      path: '/$id'
      fullPath: '/api/links/$id'
      preLoaderRoute: typeof ApiLinksIdRouteImport
      parentRoute: typeof ApiLinksRoute
    }
    '/api/campaigns/$id': {
      id: '/api/campaigns/$id'
      path: '/$id'
      fullPath: '/api/campaigns/$id'
      preLoaderRoute: typeof ApiCampaignsIdRouteImport
      parentRoute: typeof ApiCampaignsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/overview': {
      id: '/api/analytics/overview'
      path: '/api/analytics/overview'
      fullPath: '/api/analytics/overview'
      preLoaderRoute: typeof ApiAnalyticsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/export.csv': {
      id: '/api/analytics/export.csv'
      path: '/api/analytics/export.csv'
      fullPath: '/api/analytics/export.csv'
      preLoaderRoute: typeof ApiAnalyticsExportDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/tags': {
      id: '/_protected/dashboard/tags'
      path: '/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof ProtectedDashboardTagsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/settings': {
      id: '/_protected/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof ProtectedDashboardSettingsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/links': {
      id: '/_protected/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof ProtectedDashboardLinksRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/campaigns': {
      id: '/_protected/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof ProtectedDashboardCampaignsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/links/': {
      id: '/_protected/dashboard/links/'
      path: '/'
      fullPath: '/dashboard/links/'
      preLoaderRoute: typeof ProtectedDashboardLinksIndexRouteImport
      parentRoute: typeof ProtectedDashboardLinksRoute
    }
    '/api/links/$id/tags': {
      id: '/api/links/$id/tags'
      path: '/tags'
      fullPath: '/api/links/$id/tags'
      preLoaderRoute: typeof ApiLinksIdTagsRouteImport
      parentRoute: typeof ApiLinksIdRoute
    }
    '/api/links/$id/disable': {
      id: '/api/links/$id/disable'
      path: '/disable'
      fullPath: '/api/links/$id/disable'
      preLoaderRoute: typeof ApiLinksIdDisableRouteImport
      parentRoute: typeof ApiLinksIdRoute
    }
    '/api/links/$id/campaigns': {
      id: '/api/links/$id/campaigns'
      path: '/campaigns'
      fullPath: '/api/links/$id/campaigns'
      preLoaderRoute: typeof ApiLinksIdCampaignsRouteImport
      parentRoute: typeof ApiLinksIdRoute
    }
    '/api/links/$id/archive': {
      id: '/api/links/$id/archive'
      path: '/archive'
      fullPath: '/api/links/$id/archive'
      preLoaderRoute: typeof ApiLinksIdArchiveRouteImport
      parentRoute: typeof ApiLinksIdRoute
    }
    '/api/links/$id/analytics': {
      id: '/api/links/$id/analytics'
      path: '/analytics'
      fullPath: '/api/links/$id/analytics'
      preLoaderRoute: typeof ApiLinksIdAnalyticsRouteImport
      parentRoute: typeof ApiLinksIdRoute
    }
    '/_protected/dashboard/links/new': {
      id: '/_protected/dashboard/links/new'
      path: '/new'
      fullPath: '/dashboard/links/new'
      preLoaderRoute: typeof ProtectedDashboardLinksNewRouteImport
      parentRoute: typeof ProtectedDashboardLinksRoute
    }
    '/_protected/dashboard/links/$id': {
      id: '/_protected/dashboard/links/$id'
      path: '/$id'
      fullPath: '/dashboard/links/$id'
      preLoaderRoute: typeof ProtectedDashboardLinksIdRouteImport
      parentRoute: typeof ProtectedDashboardLinksRoute
    }
    '/_protected/dashboard/links/$id/edit': {
      id: '/_protected/dashboard/links/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/links/$id/edit'
      preLoaderRoute: typeof ProtectedDashboardLinksIdEditRouteImport
      parentRoute: typeof ProtectedDashboardLinksIdRoute
    }
  }
}

interface ProtectedDashboardLinksIdRouteChildren {
  ProtectedDashboardLinksIdEditRoute: typeof ProtectedDashboardLinksIdEditRoute
}

const ProtectedDashboardLinksIdRouteChildren: ProtectedDashboardLinksIdRouteChildren =
  {
    ProtectedDashboardLinksIdEditRoute: ProtectedDashboardLinksIdEditRoute,
  }

const ProtectedDashboardLinksIdRouteWithChildren =
  ProtectedDashboardLinksIdRoute._addFileChildren(
    ProtectedDashboardLinksIdRouteChildren,
  )

interface ProtectedDashboardLinksRouteChildren {
  ProtectedDashboardLinksIdRoute: typeof ProtectedDashboardLinksIdRouteWithChildren
  ProtectedDashboardLinksNewRoute: typeof ProtectedDashboardLinksNewRoute
  ProtectedDashboardLinksIndexRoute: typeof ProtectedDashboardLinksIndexRoute
}

const ProtectedDashboardLinksRouteChildren: ProtectedDashboardLinksRouteChildren =
  {
    ProtectedDashboardLinksIdRoute: ProtectedDashboardLinksIdRouteWithChildren,
    ProtectedDashboardLinksNewRoute: ProtectedDashboardLinksNewRoute,
    ProtectedDashboardLinksIndexRoute: ProtectedDashboardLinksIndexRoute,
  }

const ProtectedDashboardLinksRouteWithChildren =
  ProtectedDashboardLinksRoute._addFileChildren(
    ProtectedDashboardLinksRouteChildren,
  )

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardCampaignsRoute: typeof ProtectedDashboardCampaignsRoute
  ProtectedDashboardLinksRoute: typeof ProtectedDashboardLinksRouteWithChildren
  ProtectedDashboardSettingsRoute: typeof ProtectedDashboardSettingsRoute
  ProtectedDashboardTagsRoute: typeof ProtectedDashboardTagsRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardCampaignsRoute: ProtectedDashboardCampaignsRoute,
  ProtectedDashboardLinksRoute: ProtectedDashboardLinksRouteWithChildren,
  ProtectedDashboardSettingsRoute: ProtectedDashboardSettingsRoute,
  ProtectedDashboardTagsRoute: ProtectedDashboardTagsRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiCampaignsRouteChildren {
  ApiCampaignsIdRoute: typeof ApiCampaignsIdRoute
}

const ApiCampaignsRouteChildren: ApiCampaignsRouteChildren = {
  ApiCampaignsIdRoute: ApiCampaignsIdRoute,
}

const ApiCampaignsRouteWithChildren = ApiCampaignsRoute._addFileChildren(
  ApiCampaignsRouteChildren,
)

interface ApiLinksIdRouteChildren {
  ApiLinksIdAnalyticsRoute: typeof ApiLinksIdAnalyticsRoute
  ApiLinksIdArchiveRoute: typeof ApiLinksIdArchiveRoute
  ApiLinksIdCampaignsRoute: typeof ApiLinksIdCampaignsRoute
  ApiLinksIdDisableRoute: typeof ApiLinksIdDisableRoute
  ApiLinksIdTagsRoute: typeof ApiLinksIdTagsRoute
}

const ApiLinksIdRouteChildren: ApiLinksIdRouteChildren = {
  ApiLinksIdAnalyticsRoute: ApiLinksIdAnalyticsRoute,
  ApiLinksIdArchiveRoute: ApiLinksIdArchiveRoute,
  ApiLinksIdCampaignsRoute: ApiLinksIdCampaignsRoute,
  ApiLinksIdDisableRoute: ApiLinksIdDisableRoute,
  ApiLinksIdTagsRoute: ApiLinksIdTagsRoute,
}

const ApiLinksIdRouteWithChildren = ApiLinksIdRoute._addFileChildren(
  ApiLinksIdRouteChildren,
)

interface ApiLinksRouteChildren {
  ApiLinksIdRoute: typeof ApiLinksIdRouteWithChildren
  ApiLinksCheckPathRoute: typeof ApiLinksCheckPathRoute
}

const ApiLinksRouteChildren: ApiLinksRouteChildren = {
  ApiLinksIdRoute: ApiLinksIdRouteWithChildren,
  ApiLinksCheckPathRoute: ApiLinksCheckPathRoute,
}

const ApiLinksRouteWithChildren = ApiLinksRoute._addFileChildren(
  ApiLinksRouteChildren,
)

interface ApiTagsRouteChildren {
  ApiTagsIdRoute: typeof ApiTagsIdRoute
}

const ApiTagsRouteChildren: ApiTagsRouteChildren = {
  ApiTagsIdRoute: ApiTagsIdRoute,
}

const ApiTagsRouteWithChildren =
  ApiTagsRoute._addFileChildren(ApiTagsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortPathRoute: ShortPathRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ApiCampaignsRoute: ApiCampaignsRouteWithChildren,
  ApiLinksRoute: ApiLinksRouteWithChildren,
  ApiTagsRoute: ApiTagsRouteWithChildren,
  ApiAnalyticsExportDotcsvRoute: ApiAnalyticsExportDotcsvRoute,
  ApiAnalyticsOverviewRoute: ApiAnalyticsOverviewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
